"""Original, deterministic curriculum specifications for the offline academy."""

from __future__ import annotations


ACADEMY_TRACKS = (
    ("computer-literacy", "Literacia computacional", "Do problema ao modelo executável, ficheiros e recursos locais.", "python", 0),
    ("logic-pseudocode", "Lógica e pseudocódigo", "Raciocínio booleano, traçado e máquinas de estados.", "python", 1),
    ("python-foundations", "Python: bases", "Valores, decisões, funções e resultados observáveis.", "python", 2),
    ("python-oop", "Python: POO", "Objetos, invariantes, composição e desenho testável.", "python", 3),
    ("python-algorithms", "Algoritmos", "Correção, complexidade, pesquisa e transformação determinística.", "python", 4),
    ("python-data-structures", "Estruturas de dados", "Escolha consciente de sequências, mapas, conjuntos e árvores.", "python", 5),
    ("math-programming", "Matemática para programação", "Matemática discreta, probabilidade e álgebra linear aplicadas.", "python", 6),
    ("testing-debugging", "Testes, debugging e qualidade", "Contratos, casos-limite e localização sistemática de falhas.", "python", 7),
    ("python-advanced", "Python avançado e sistemas", "Iteração lazy, instrumentação e concorrência controlada.", "python", 8),
    ("sql-databases", "SQL e bases de dados", "Modelação relacional, consultas e atomicidade por simulação local.", "sql", 9),
    ("web-apis", "Web, APIs e frameworks Python", "HTTP, validação e routing com princípios transferíveis.", "web", 10),
    ("data-ai", "Dados e inteligência artificial", "Pipelines, ML clássico, redes neuronais e agentes auditáveis.", "python", 11),
)


# slug, track, title, observable objective, essential explanation,
# starter code and isolated executable test. All exercises use only Python's
# standard semantics so the core course remains genuinely offline/sandboxed.
ACADEMY_MODULES = (
    ("resources-and-files", "computer-literacy", "Recursos e persistência",
     "Classificar CPU, memória e armazenamento num cenário concreto.",
     "CPU executa instruções, memória sustenta o estado de trabalho e armazenamento preserva dados depois do processo terminar.",
     "def classificar_recurso(descricao):\n    pass\n",
     "assert classificar_recurso('cálculo imediato') == 'cpu'\nassert classificar_recurso('estado temporário') == 'memoria'\nassert classificar_recurso('guardar ficheiro') == 'armazenamento'"),
    ("problem-decomposition", "computer-literacy", "Decomposição de problemas",
     "Separar entrada, transformação e saída sem perder o contrato.",
     "Uma decomposição útil atribui a cada passo uma responsabilidade observável e mantém explícito o valor que passa ao passo seguinte.",
     "def decompor(pedido):\n    pass\n",
     "assert decompor('somar dois valores') == ['ler valores', 'somar valores', 'mostrar resultado']"),
    ("data-representation", "computer-literacy", "Representação de dados",
     "Normalizar um inteiro para o intervalo de um byte.",
     "Uma representação possui limites. Validar o intervalo antes de persistir evita estados que o formato não consegue representar.",
     "def limitar_byte(valor):\n    pass\n",
     "assert limitar_byte(-2) == 0\nassert limitar_byte(42) == 42\nassert limitar_byte(999) == 255"),
    ("boolean-reasoning", "logic-pseudocode", "Lógica booleana",
     "Contar condições verdadeiras sem confundir valor e identidade.",
     "Conjunção exige todas as condições; disjunção exige pelo menos uma; negação inverte exatamente um valor lógico.",
     "def contar_verdadeiros(condicoes):\n    pass\n",
     "assert contar_verdadeiros([True, False, True]) == 2\nassert contar_verdadeiros([]) == 0"),
    ("pseudocode-tracing", "logic-pseudocode", "Traçado de pseudocódigo",
     "Produzir o estado do acumulador após cada passo.",
     "Traçar um algoritmo significa registar, por ordem, apenas as alterações de estado relevantes; isso torna erros reproduzíveis.",
     "def traco_somas(valores):\n    pass\n",
     "assert traco_somas([2, 3, -1]) == [2, 5, 4]\nassert traco_somas([]) == []"),
    ("finite-state-machines", "logic-pseudocode", "Máquinas de estados",
     "Aplicar transições válidas e rejeitar eventos impossíveis.",
     "Uma máquina de estados define pares estado-evento permitidos; uma transição ausente deve conservar o estado ou falhar segundo o contrato.",
     "def proximo_estado(estado, evento):\n    pass\n",
     "assert proximo_estado('parado', 'iniciar') == 'ativo'\nassert proximo_estado('ativo', 'pausar') == 'pausado'\nassert proximo_estado('parado', 'pausar') == 'parado'"),
    ("composition-over-inheritance", "python-oop", "Composição e colaboração",
     "Construir um serviço que delega o registo num objeto colaborador.",
     "Composição liga objetos por contratos pequenos e permite substituir dependências sem criar uma hierarquia rígida.",
     "class Registo:\n    def __init__(self): self.itens = []\n    def adicionar(self, item): self.itens.append(item)\n\nclass Servico:\n    pass\n",
     "r = Registo()\ns = Servico(r)\ns.processar('ok')\nassert r.itens == ['ok']"),
    ("complexity-growth", "python-algorithms", "Crescimento e complexidade",
     "Contar comparações de uma pesquisa linear.",
     "Complexidade descreve como o trabalho cresce com a entrada. Medir operações dominantes permite comparar algoritmos sem depender do computador.",
     "def pesquisar_com_custo(valores, alvo):\n    pass\n",
     "assert pesquisar_com_custo([4, 7, 9], 7) == (1, 2)\nassert pesquisar_com_custo([4, 7], 0) == (-1, 2)"),
    ("trees-and-traversal", "python-data-structures", "Árvores e percursos",
     "Percorrer uma árvore representada por pares valor-filhos em profundidade.",
     "Uma árvore expressa hierarquia. Um percurso em profundidade visita o nó antes dos filhos e preserva uma ordem determinística.",
     "def pre_ordem(arvore):\n    pass\n",
     "a = ('A', [('B', []), ('C', [('D', [])])])\nassert pre_ordem(a) == ['A', 'B', 'C', 'D']"),
    ("sets-and-relations", "math-programming", "Conjuntos e relações",
     "Calcular união, interseção e diferença com resultados estáveis.",
     "Conjuntos modelam pertença; união combina, interseção conserva o comum e diferença remove o que pertence ao segundo conjunto.",
     "def operacoes_conjunto(a, b):\n    pass\n",
     "assert operacoes_conjunto({1,2}, {2,3}) == ({1,2,3}, {2}, {1})"),
    ("probability-summary", "math-programming", "Probabilidade e estatística",
     "Calcular média e probabilidade empírica de um evento.",
     "A média resume magnitude; frequência relativa estima probabilidade a partir de observações e deve declarar o caso sem dados.",
     "def resumo(valores, alvo):\n    pass\n",
     "assert resumo([1,2,2,3], 2) == (2.0, 0.5)\nassert resumo([], 2) == (None, 0.0)"),
    ("vectors-and-dot-product", "math-programming", "Vetores e produto interno",
     "Validar dimensões e calcular um produto interno.",
     "O produto interno soma produtos coordenada a coordenada; dimensões incompatíveis não definem essa operação.",
     "def produto_interno(a, b):\n    pass\n",
     "assert produto_interno([1,2,3], [4,0,-1]) == 1\ntry:\n produto_interno([1], [1,2])\n assert False\nexcept ValueError: pass"),
    ("contracts-and-errors", "testing-debugging", "Contratos e erros",
     "Implementar divisão com validação explícita do denominador.",
     "Pré-condições descrevem entradas aceites; pós-condições descrevem o resultado; erros específicos tornam violações diagnosticáveis.",
     "def dividir_seguro(a, b):\n    pass\n",
     "assert dividir_seguro(6, 3) == 2\ntry:\n dividir_seguro(1, 0)\n assert False\nexcept ValueError: pass"),
    ("boundary-test-design", "testing-debugging", "Desenho de casos-limite",
     "Gerar casos imediatamente abaixo, na fronteira e acima dela.",
     "Uma fronteira muda o comportamento. Testá-la com três valores adjacentes expõe comparações inclusivas e exclusivas incorretas.",
     "def casos_fronteira(limite):\n    pass\n",
     "assert casos_fronteira(18) == [17, 18, 19]"),
    ("debug-first-divergence", "testing-debugging", "Primeira divergência",
     "Localizar a primeira posição diferente entre resultado e expectativa.",
     "Um bom diagnóstico reduz o problema ao primeiro estado observável que diverge, em vez de explicar efeitos posteriores.",
     "def primeira_diferenca(obtido, esperado):\n    pass\n",
     "assert primeira_diferenca([1,9,3], [1,2,3]) == 1\nassert primeira_diferenca([1], [1]) is None\nassert primeira_diferenca([1], [1,2]) == 1"),
    ("lazy-iteration", "python-advanced", "Iteração lazy",
     "Dividir uma sequência em blocos produzidos sob procura.",
     "Um iterador lazy produz cada valor apenas quando solicitado, reduzindo memória e permitindo pipelines sobre entradas longas.",
     "def blocos(valores, tamanho):\n    pass\n",
     "assert list(blocos([1,2,3,4,5], 2)) == [[1,2],[3,4],[5]]\ntry:\n list(blocos([1], 0)); assert False\nexcept ValueError: pass"),
    ("function-instrumentation", "python-advanced", "Instrumentação de funções",
     "Criar um decorador que conta chamadas sem alterar o resultado.",
     "Um decorador envolve um contrato existente; deve preservar argumentos, resultado e uma métrica observável separada.",
     "def contar_chamadas(funcao):\n    pass\n",
     "@contar_chamadas\ndef dobro(x): return x*2\nassert dobro(3) == 6\nassert dobro(4) == 8\nassert dobro.chamadas == 2"),
    ("bounded-scheduling", "python-advanced", "Concorrência limitada",
     "Agrupar tarefas por um limite máximo de trabalho simultâneo.",
     "Concorrência segura começa por um limite explícito; lotes determinísticos permitem raciocinar sobre pressão e recuperação.",
     "def lotes(tarefas, limite):\n    pass\n",
     "assert lotes(['a','b','c','d','e'], 2) == [['a','b'],['c','d'],['e']]"),
    ("relational-keys", "sql-databases", "Relações e chaves",
     "Detetar chaves repetidas antes de inserir linhas.",
     "Uma chave primária identifica uma linha; validar unicidade protege referências e evita que duas entidades disputem a mesma identidade.",
     "def chaves_repetidas(linhas, campo='id'):\n    pass\n",
     "assert chaves_repetidas([{'id':1},{'id':2},{'id':1}]) == {1}\nassert chaves_repetidas([], 'id') == set()"),
    ("query-pipeline", "sql-databases", "Pipeline de consulta",
     "Filtrar e projetar linhas sem alterar os registos originais.",
     "Uma consulta combina seleção de linhas e projeção de colunas; a ordem dessas operações altera custo e, por vezes, significado.",
     "def consultar(linhas, predicado, campos):\n    pass\n",
     "dados=[{'id':1,'ativo':True,'x':9},{'id':2,'ativo':False,'x':8}]\nassert consultar(dados, lambda r:r['ativo'], ('id','x')) == [{'id':1,'x':9}]"),
    ("atomic-transactions", "sql-databases", "Transações atómicas",
     "Aplicar operações numa cópia e reverter o lote quando uma falha.",
     "Atomicidade significa tudo ou nada. Alterações só se tornam visíveis depois de todas as validações terminarem com sucesso.",
     "def aplicar_atomico(estado, operacoes):\n    pass\n",
     "e={'saldo':10}\nassert aplicar_atomico(e,[lambda x:x.update(saldo=12)]) == {'saldo':12}\nassert e == {'saldo':10}"),
    ("http-semantics", "web-apis", "Semântica HTTP",
     "Classificar códigos de estado pelas respetivas famílias.",
     "Códigos 2xx indicam sucesso, 4xx problemas no pedido e 5xx falhas do servidor; o contrato deve rejeitar valores fora do intervalo.",
     "def familia_http(codigo):\n    pass\n",
     "assert familia_http(201) == 'sucesso'\nassert familia_http(404) == 'cliente'\nassert familia_http(503) == 'servidor'"),
    ("api-validation", "web-apis", "Validação de APIs",
     "Validar campos obrigatórios e tipos antes de executar lógica.",
     "A fronteira da API transforma dados não confiáveis num contrato interno; erros devem indicar campos sem expor detalhes privados.",
     "def validar_utilizador(payload):\n    pass\n",
     "assert validar_utilizador({'nome':'Ana','idade':20}) == {}\nassert validar_utilizador({'nome':'','idade':'20'}) == {'nome':'obrigatorio','idade':'inteiro'}"),
    ("framework-routing", "web-apis", "Routing em Django e FastAPI",
     "Escolher uma função a partir de método e caminho sem executar rede.",
     "Frameworks associam método e caminho a handlers; separar tabela de rotas e execução torna conflitos testáveis.",
     "def resolver_rota(rotas, metodo, caminho):\n    pass\n",
     "rotas={('GET','/estado'):'estado',('POST','/itens'):'criar'}\nassert resolver_rota(rotas,'GET','/estado') == 'estado'\nassert resolver_rota(rotas,'DELETE','/x') is None"),
    ("data-pipelines", "data-ai", "Pipelines de dados",
     "Limpar valores ausentes e normalizar números para zero a um.",
     "Um pipeline reproduzível declara entrada, política para ausentes, transformação e metadados necessários para repetir a operação.",
     "def normalizar(valores):\n    pass\n",
     "assert normalizar([None, 10, 20, 30]) == [0.0,0.5,1.0]\nassert normalizar([5,5]) == [0.0,0.0]"),
    ("classical-ml", "data-ai", "Machine Learning clássico",
     "Classificar um ponto pelo centróide unidimensional mais próximo.",
     "Um classificador por centróides resume cada classe por uma referência e torna a distância e a decisão inteiramente auditáveis.",
     "def centroide_por_classe(amostras):\n    pass\n\ndef prever(centroides, valor):\n    pass\n",
     "c=centroide_por_classe([('a',0),('a',2),('b',8),('b',10)])\nassert c == {'a':1.0,'b':9.0}\nassert prever(c, 7) == 'b'"),
    ("neural-agents", "data-ai", "Neurónios e agentes auditáveis",
     "Calcular um neurónio linear com ReLU e devolver também a decisão.",
     "Um neurónio combina entradas e pesos, soma bias e aplica ativação. Um agente auditável conserva o valor que justificou a ação.",
     "def neuronio_relu(entradas, pesos, bias):\n    pass\n\ndef decidir(valor, limiar):\n    pass\n",
     "assert neuronio_relu([2,-1],[0.5,2],1) == 0\nassert neuronio_relu([2,1],[0.5,2],1) == 4\nassert decidir(4,3) == {'acao':'agir','valor':4}"),
)
