"""Original, deterministic curriculum specifications for the offline academy."""

from __future__ import annotations


ACADEMY_TRACKS = (
    ("computer-literacy", "Literacia computacional", "Do problema ao modelo executável, ficheiros e recursos locais.", "python", 0),
    ("logic-pseudocode", "Lógica e pseudocódigo", "Raciocínio booleano, traçado e máquinas de estados.", "python", 1),
    ("python-foundations", "Python: bases", "Valores, decisões, funções e resultados observáveis.", "python", 2),
    ("python-oop", "Python: POO", "Objetos, invariantes, composição e desenho testável.", "python", 3),
    ("python-algorithms", "Algoritmos", "Correção, complexidade, pesquisa e transformação determinística.", "python", 4),
    ("python-data-structures", "Estruturas de dados", "Escolha consciente de sequências, mapas, conjuntos e árvores.", "python", 5),
    ("math-programming", "Matemática para programação", "Matemática discreta, probabilidade e álgebra linear aplicadas.", "python", 6),
    ("testing-debugging", "Testes, debugging e qualidade", "Contratos, casos-limite e localização sistemática de falhas.", "python", 7),
    ("python-advanced", "Python avançado e sistemas", "Iteração lazy, instrumentação e concorrência controlada.", "python", 8),
    ("sql-databases", "SQL e bases de dados", "Modelação relacional, consultas e atomicidade por simulação local.", "sql", 9),
    ("web-apis", "Web, APIs e frameworks Python", "HTTP, validação e routing com princípios transferíveis.", "web", 10),
    ("data-ai", "Dados e inteligência artificial", "Pipelines, ML clássico, redes neuronais e agentes auditáveis.", "python", 11),
)


# slug, track, title, observable objective, essential explanation,
# starter code and isolated executable test. All exercises use only Python's
# standard semantics so the core course remains genuinely offline/sandboxed.
_ACADEMY_MODULES_BASE = (
    ("resources-and-files", "computer-literacy", "Recursos e persistência",
     "Classificar CPU, memória e armazenamento num cenário concreto.",
     "CPU executa instruções, memória sustenta o estado de trabalho e armazenamento preserva dados depois do processo terminar.",
     "def classificar_recurso(descricao):\n    pass\n",
     "assert classificar_recurso('cálculo imediato') == 'cpu'\nassert classificar_recurso('estado temporário') == 'memoria'\nassert classificar_recurso('guardar ficheiro') == 'armazenamento'"),
    ("problem-decomposition", "computer-literacy", "Decomposição de problemas",
     "Separar entrada, transformação e saída sem perder o contrato.",
     "Uma decomposição útil atribui a cada passo uma responsabilidade observável e mantém explícito o valor que passa ao passo seguinte.",
     "def decompor(pedido):\n    pass\n",
     "assert decompor('somar dois valores') == ['ler valores', 'somar valores', 'mostrar resultado']"),
    ("data-representation", "computer-literacy", "Representação de dados",
     "Normalizar um inteiro para o intervalo de um byte.",
     "Uma representação possui limites. Validar o intervalo antes de persistir evita estados que o formato não consegue representar.",
     "def limitar_byte(valor):\n    pass\n",
     "assert limitar_byte(-2) == 0\nassert limitar_byte(42) == 42\nassert limitar_byte(999) == 255"),
    ("boolean-reasoning", "logic-pseudocode", "Lógica booleana",
     "Contar condições verdadeiras sem confundir valor e identidade.",
     "Conjunção exige todas as condições; disjunção exige pelo menos uma; negação inverte exatamente um valor lógico.",
     "def contar_verdadeiros(condicoes):\n    pass\n",
     "assert contar_verdadeiros([True, False, True]) == 2\nassert contar_verdadeiros([]) == 0"),
    ("pseudocode-tracing", "logic-pseudocode", "Traçado de pseudocódigo",
     "Produzir o estado do acumulador após cada passo.",
     "Traçar um algoritmo significa registar, por ordem, apenas as alterações de estado relevantes; isso torna erros reproduzíveis.",
     "def traco_somas(valores):\n    pass\n",
     "assert traco_somas([2, 3, -1]) == [2, 5, 4]\nassert traco_somas([]) == []"),
    ("finite-state-machines", "logic-pseudocode", "Máquinas de estados",
     "Aplicar transições válidas e rejeitar eventos impossíveis.",
     "Uma máquina de estados define pares estado-evento permitidos; uma transição ausente deve conservar o estado ou falhar segundo o contrato.",
     "def proximo_estado(estado, evento):\n    pass\n",
     "assert proximo_estado('parado', 'iniciar') == 'ativo'\nassert proximo_estado('ativo', 'pausar') == 'pausado'\nassert proximo_estado('parado', 'pausar') == 'parado'"),
    ("composition-over-inheritance", "python-oop", "Composição e colaboração",
     "Construir um serviço que delega o registo num objeto colaborador.",
     "Composição liga objetos por contratos pequenos e permite substituir dependências sem criar uma hierarquia rígida.",
     "class Registo:\n    def __init__(self): self.itens = []\n    def adicionar(self, item): self.itens.append(item)\n\nclass Servico:\n    pass\n",
     "r = Registo()\ns = Servico(r)\ns.processar('ok')\nassert r.itens == ['ok']"),
    ("complexity-growth", "python-algorithms", "Crescimento e complexidade",
     "Contar comparações de uma pesquisa linear.",
     "Complexidade descreve como o trabalho cresce com a entrada. Medir operações dominantes permite comparar algoritmos sem depender do computador.",
     "def pesquisar_com_custo(valores, alvo):\n    pass\n",
     "assert pesquisar_com_custo([4, 7, 9], 7) == (1, 2)\nassert pesquisar_com_custo([4, 7], 0) == (-1, 2)"),
    ("trees-and-traversal", "python-data-structures", "Árvores e percursos",
     "Percorrer uma árvore representada por pares valor-filhos em profundidade.",
     "Uma árvore expressa hierarquia. Um percurso em profundidade visita o nó antes dos filhos e preserva uma ordem determinística.",
     "def pre_ordem(arvore):\n    pass\n",
     "a = ('A', [('B', []), ('C', [('D', [])])])\nassert pre_ordem(a) == ['A', 'B', 'C', 'D']"),
    ("sets-and-relations", "math-programming", "Conjuntos e relações",
     "Calcular união, interseção e diferença com resultados estáveis.",
     "Conjuntos modelam pertença; união combina, interseção conserva o comum e diferença remove o que pertence ao segundo conjunto.",
     "def operacoes_conjunto(a, b):\n    pass\n",
     "assert operacoes_conjunto({1,2}, {2,3}) == ({1,2,3}, {2}, {1})"),
    ("probability-summary", "math-programming", "Probabilidade e estatística",
     "Calcular média e probabilidade empírica de um evento.",
     "A média resume magnitude; frequência relativa estima probabilidade a partir de observações e deve declarar o caso sem dados.",
     "def resumo(valores, alvo):\n    pass\n",
     "assert resumo([1,2,2,3], 2) == (2.0, 0.5)\nassert resumo([], 2) == (None, 0.0)"),
    ("vectors-and-dot-product", "math-programming", "Vetores e produto interno",
     "Validar dimensões e calcular um produto interno.",
     "O produto interno soma produtos coordenada a coordenada; dimensões incompatíveis não definem essa operação.",
     "def produto_interno(a, b):\n    pass\n",
     "assert produto_interno([1,2,3], [4,0,-1]) == 1\ntry:\n produto_interno([1], [1,2])\n assert False\nexcept ValueError: pass"),
    ("contracts-and-errors", "testing-debugging", "Contratos e erros",
     "Implementar divisão com validação explícita do denominador.",
     "Pré-condições descrevem entradas aceites; pós-condições descrevem o resultado; erros específicos tornam violações diagnosticáveis.",
     "def dividir_seguro(a, b):\n    pass\n",
     "assert dividir_seguro(6, 3) == 2\ntry:\n dividir_seguro(1, 0)\n assert False\nexcept ValueError: pass"),
    ("boundary-test-design", "testing-debugging", "Desenho de casos-limite",
     "Gerar casos imediatamente abaixo, na fronteira e acima dela.",
     "Uma fronteira muda o comportamento. Testá-la com três valores adjacentes expõe comparações inclusivas e exclusivas incorretas.",
     "def casos_fronteira(limite):\n    pass\n",
     "assert casos_fronteira(18) == [17, 18, 19]"),
    ("debug-first-divergence", "testing-debugging", "Primeira divergência",
     "Localizar a primeira posição diferente entre resultado e expectativa.",
     "Um bom diagnóstico reduz o problema ao primeiro estado observável que diverge, em vez de explicar efeitos posteriores.",
     "def primeira_diferenca(obtido, esperado):\n    pass\n",
     "assert primeira_diferenca([1,9,3], [1,2,3]) == 1\nassert primeira_diferenca([1], [1]) is None\nassert primeira_diferenca([1], [1,2]) == 1"),
    ("lazy-iteration", "python-advanced", "Iteração lazy",
     "Dividir uma sequência em blocos produzidos sob procura.",
     "Um iterador lazy produz cada valor apenas quando solicitado, reduzindo memória e permitindo pipelines sobre entradas longas.",
     "def blocos(valores, tamanho):\n    pass\n",
     "assert list(blocos([1,2,3,4,5], 2)) == [[1,2],[3,4],[5]]\ntry:\n list(blocos([1], 0)); assert False\nexcept ValueError: pass"),
    ("function-instrumentation", "python-advanced", "Instrumentação de funções",
     "Criar um decorador que conta chamadas sem alterar o resultado.",
     "Um decorador envolve um contrato existente; deve preservar argumentos, resultado e uma métrica observável separada.",
     "def contar_chamadas(funcao):\n    pass\n",
     "@contar_chamadas\ndef dobro(x): return x*2\nassert dobro(3) == 6\nassert dobro(4) == 8\nassert dobro.chamadas == 2"),
    ("bounded-scheduling", "python-advanced", "Concorrência limitada",
     "Agrupar tarefas por um limite máximo de trabalho simultâneo.",
     "Concorrência segura começa por um limite explícito; lotes determinísticos permitem raciocinar sobre pressão e recuperação.",
     "def lotes(tarefas, limite):\n    pass\n",
     "assert lotes(['a','b','c','d','e'], 2) == [['a','b'],['c','d'],['e']]"),
    ("relational-keys", "sql-databases", "Relações e chaves",
     "Detetar chaves repetidas antes de inserir linhas.",
     "Uma chave primária identifica uma linha; validar unicidade protege referências e evita que duas entidades disputem a mesma identidade.",
     "def chaves_repetidas(linhas, campo='id'):\n    pass\n",
     "assert chaves_repetidas([{'id':1},{'id':2},{'id':1}]) == {1}\nassert chaves_repetidas([], 'id') == set()"),
    ("query-pipeline", "sql-databases", "Pipeline de consulta",
     "Filtrar e projetar linhas sem alterar os registos originais.",
     "Uma consulta combina seleção de linhas e projeção de colunas; a ordem dessas operações altera custo e, por vezes, significado.",
     "def consultar(linhas, predicado, campos):\n    pass\n",
     "dados=[{'id':1,'ativo':True,'x':9},{'id':2,'ativo':False,'x':8}]\nassert consultar(dados, lambda r:r['ativo'], ('id','x')) == [{'id':1,'x':9}]"),
    ("atomic-transactions", "sql-databases", "Transações atómicas",
     "Aplicar operações numa cópia e reverter o lote quando uma falha.",
     "Atomicidade significa tudo ou nada. Alterações só se tornam visíveis depois de todas as validações terminarem com sucesso.",
     "def aplicar_atomico(estado, operacoes):\n    pass\n",
     "e={'saldo':10}\nassert aplicar_atomico(e,[lambda x:x.update(saldo=12)]) == {'saldo':12}\nassert e == {'saldo':10}"),
    ("http-semantics", "web-apis", "Semântica HTTP",
     "Classificar códigos de estado pelas respetivas famílias.",
     "Códigos 2xx indicam sucesso, 4xx problemas no pedido e 5xx falhas do servidor; o contrato deve rejeitar valores fora do intervalo.",
     "def familia_http(codigo):\n    pass\n",
     "assert familia_http(201) == 'sucesso'\nassert familia_http(404) == 'cliente'\nassert familia_http(503) == 'servidor'"),
    ("api-validation", "web-apis", "Validação de APIs",
     "Validar campos obrigatórios e tipos antes de executar lógica.",
     "A fronteira da API transforma dados não confiáveis num contrato interno; erros devem indicar campos sem expor detalhes privados.",
     "def validar_utilizador(payload):\n    pass\n",
     "assert validar_utilizador({'nome':'Ana','idade':20}) == {}\nassert validar_utilizador({'nome':'','idade':'20'}) == {'nome':'obrigatorio','idade':'inteiro'}"),
    ("framework-routing", "web-apis", "Routing em Django e FastAPI",
     "Escolher uma função a partir de método e caminho sem executar rede.",
     "Frameworks associam método e caminho a handlers; separar tabela de rotas e execução torna conflitos testáveis.",
     "def resolver_rota(rotas, metodo, caminho):\n    pass\n",
     "rotas={('GET','/estado'):'estado',('POST','/itens'):'criar'}\nassert resolver_rota(rotas,'GET','/estado') == 'estado'\nassert resolver_rota(rotas,'DELETE','/x') is None"),
    ("data-pipelines", "data-ai", "Pipelines de dados",
     "Limpar valores ausentes e normalizar números para zero a um.",
     "Um pipeline reproduzível declara entrada, política para ausentes, transformação e metadados necessários para repetir a operação.",
     "def normalizar(valores):\n    pass\n",
     "assert normalizar([None, 10, 20, 30]) == [0.0,0.5,1.0]\nassert normalizar([5,5]) == [0.0,0.0]"),
    ("classical-ml", "data-ai", "Machine Learning clássico",
     "Classificar um ponto pelo centróide unidimensional mais próximo.",
     "Um classificador por centróides resume cada classe por uma referência e torna a distância e a decisão inteiramente auditáveis.",
     "def centroide_por_classe(amostras):\n    pass\n\ndef prever(centroides, valor):\n    pass\n",
     "c=centroide_por_classe([('a',0),('a',2),('b',8),('b',10)])\nassert c == {'a':1.0,'b':9.0}\nassert prever(c, 7) == 'b'"),
    ("neural-agents", "data-ai", "Neurónios e agentes auditáveis",
     "Calcular um neurónio linear com ReLU e devolver também a decisão.",
     "Um neurónio combina entradas e pesos, soma bias e aplica ativação. Um agente auditável conserva o valor que justificou a ação.",
     "def neuronio_relu(entradas, pesos, bias):\n    pass\n\ndef decidir(valor, limiar):\n    pass\n",
     "assert neuronio_relu([2,-1],[0.5,2],1) == 0\nassert neuronio_relu([2,1],[0.5,2],1) == 4\nassert decidir(4,3) == {'acao':'agir','valor':4}"),
)


# The vertical core spends the remaining 1.0 unit budget on the four tracks
# that must take a learner from first principles to independent problem
# solving. Every statement is original Aprendix copy; approved books orient
# coverage and terminology but their text and exercises are never copied.
VERTICAL_CORE_MODULES = (
    ("types-and-conversion", "python-foundations", "Tipos e conversão segura",
     "Converter texto em valores apenas depois de validar o formato esperado.",
     "Conversão é uma fronteira de contrato: distingue ausência, formato inválido e valor válido, sem esconder erros com exceções demasiado amplas.",
     "def inteiro_ou(texto, predefinido=None):\n    pass\n",
     "assert inteiro_ou(' 42 ') == 42\nassert inteiro_ou('-7') == -7\nassert inteiro_ou('4.2', 0) == 0\nassert inteiro_ou('', 9) == 9"),
    ("string-normalization", "python-foundations", "Texto e normalização",
     "Normalizar espaços e capitalização preservando as palavras do utilizador.",
     "Strings são sequências imutáveis. Um pipeline previsível separa limpeza, transformação e validação para não perder informação silenciosamente.",
     "def normalizar_nome(texto):\n    pass\n",
     "assert normalizar_nome('  ana   SILVA ') == 'Ana Silva'\nassert normalizar_nome('joão') == 'João'\nassert normalizar_nome('   ') == ''"),
    ("loops-and-accumulators", "python-foundations", "Ciclos e acumuladores",
     "Calcular soma e quantidade de valores positivos numa única passagem.",
     "Um acumulador tem valor inicial, regra de atualização e invariante. Declarar os três evita erros de fronteira e torna o ciclo explicável.",
     "def resumo_positivos(valores):\n    pass\n",
     "assert resumo_positivos([-2, 3, 0, 5]) == (8, 2)\nassert resumo_positivos([]) == (0, 0)\nassert resumo_positivos([-1]) == (0, 0)"),
    ("function-contracts", "python-foundations", "Funções e contratos",
     "Implementar uma função total que devolve o preço final sem alterar os argumentos.",
     "Uma função pequena declara entradas, resultado e erros. Ser total significa definir o comportamento para todas as entradas aceites pelo contrato.",
     "def preco_final(preco, desconto=0):\n    pass\n",
     "assert preco_final(100, 20) == 80\nassert preco_final(12.5) == 12.5\ntry:\n preco_final(-1); assert False\nexcept ValueError: pass\ntry:\n preco_final(10, 101); assert False\nexcept ValueError: pass"),
    ("collections-and-slicing", "python-foundations", "Coleções e slicing",
     "Devolver uma nova sequência rodada sem modificar a lista recebida.",
     "Listas representam ordem mutável; slicing cria segmentos novos. Normalizar o deslocamento com o comprimento cobre rotações grandes e negativas.",
     "def rodar(valores, passos):\n    pass\n",
     "dados=[1,2,3,4]\nassert rodar(dados, 1) == [4,1,2,3]\nassert rodar(dados, -1) == [2,3,4,1]\nassert rodar([], 7) == []\nassert dados == [1,2,3,4]"),
    ("records-and-lines", "python-foundations", "Registos e linhas",
     "Interpretar linhas chave=valor, ignorando linhas vazias e rejeitando duplicados.",
     "Separar parsing de acesso a ficheiros permite testar a transformação sem depender do disco. Cada linha válida produz exatamente uma chave e um valor.",
     "def interpretar_linhas(linhas):\n    pass\n",
     "assert interpretar_linhas(['nome=Ana','', 'idade=20']) == {'nome':'Ana','idade':'20'}\ntry:\n interpretar_linhas(['x=1','x=2']); assert False\nexcept ValueError: pass\ntry:\n interpretar_linhas(['sem separador']); assert False\nexcept ValueError: pass"),
    ("constructors-and-validation", "python-oop", "Construção e invariantes",
     "Criar uma Conta que rejeita saldo inicial negativo e depósitos não positivos.",
     "O construtor estabelece o primeiro estado válido. Cada método público confirma as pré-condições antes de alterar esse estado.",
     "class Conta:\n    pass\n",
     "c=Conta(10)\nassert c.saldo == 10\nc.depositar(5)\nassert c.saldo == 15\ntry:\n Conta(-1); assert False\nexcept ValueError: pass\ntry:\n c.depositar(0); assert False\nexcept ValueError: pass"),
    ("properties-and-encapsulation", "python-oop", "Propriedades e encapsulamento",
     "Expor temperatura em Celsius e Fahrenheit mantendo uma única representação interna.",
     "Uma property protege o contrato de acesso sem duplicar estado. Representações derivadas devem ser calculadas a partir de uma fonte de verdade.",
     "class Temperatura:\n    pass\n",
     "t=Temperatura(0)\nassert t.celsius == 0\nassert t.fahrenheit == 32\nt.fahrenheit = 212\nassert round(t.celsius, 6) == 100"),
    ("inheritance-and-polymorphism", "python-oop", "Polimorfismo por contrato",
     "Calcular o total de formas diferentes através do mesmo método area().",
     "Polimorfismo permite que o consumidor dependa do comportamento e não de testes de tipo. Cada forma preserva o contrato area sem ramificação externa.",
     "class Retangulo:\n    pass\n\nclass Circulo:\n    pass\n\ndef area_total(formas):\n    pass\n",
     "r=Retangulo(3,4)\nc=Circulo(1)\nassert r.area() == 12\nassert round(c.area(), 5) == 3.14159\nassert round(area_total([r,c]),5) == 15.14159"),
    ("dunder-protocols", "python-oop", "Protocolos e métodos especiais",
     "Implementar uma Colecao que suporta len, iteração e representação sem expor a lista interna.",
     "Métodos especiais integram objetos nos protocolos da linguagem. Devolver um iterador e uma cópia evita fuga acidental do estado mutável.",
     "class Colecao:\n    pass\n",
     "c=Colecao([2,4,6])\nassert len(c) == 3\nassert list(c) == [2,4,6]\nassert repr(c) == 'Colecao(3 itens)'\nexterno=c.itens\nexterno.append(8)\nassert list(c) == [2,4,6]"),
    ("class-and-static-methods", "python-oop", "Métodos de classe e fábricas",
     "Construir Produto a partir de texto e validar códigos sem depender de uma instância.",
     "Um classmethod cria instâncias respeitando subclasses; um staticmethod representa uma operação coesa que não usa estado de classe nem de instância.",
     "class Produto:\n    pass\n",
     "p=Produto.de_texto('A17;Teclado;39.90')\nassert (p.codigo,p.nome,p.preco) == ('A17','Teclado',39.9)\nassert Produto.codigo_valido('A17')\nassert not Produto.codigo_valido('17')"),
    ("binary-search-invariant", "python-algorithms", "Pesquisa binária",
     "Encontrar a primeira ocorrência num vetor ordenado em tempo logarítmico.",
     "O intervalo de procura conserva o invariante de que uma resposta possível permanece entre os limites. Ao encontrar o alvo, continua à esquerda.",
     "def primeira_posicao_ordenada(valores, alvo):\n    pass\n",
     "assert primeira_posicao_ordenada([1,2,2,2,5],2) == 1\nassert primeira_posicao_ordenada([1,3,7],4) == -1\nassert primeira_posicao_ordenada([],1) == -1"),
    ("elementary-sorting", "python-algorithms", "Ordenação elementar",
     "Ordenar uma cópia por inserção e contabilizar deslocamentos.",
     "Na inserção, o prefixo anterior ao índice corrente permanece ordenado. A contagem de deslocamentos torna o custo observável.",
     "def ordenar_insercao(valores):\n    pass\n",
     "dados=[3,1,2]\nassert ordenar_insercao(dados) == ([1,2,3],2)\nassert dados == [3,1,2]\nassert ordenar_insercao([]) == ([],0)"),
    ("divide-and-conquer", "python-algorithms", "Dividir e conquistar",
     "Intercalar duas sequências ordenadas preservando repetições e estabilidade.",
     "Dividir e conquistar depende de uma combinação correta. No merge, o menor elemento frontal é seguro para o próximo lugar do resultado.",
     "def intercalar_ordenados(a, b):\n    pass\n",
     "assert intercalar_ordenados([1,3,3],[2,3,4]) == [1,2,3,3,3,4]\nassert intercalar_ordenados([], [2]) == [2]\nassert intercalar_ordenados([],[]) == []"),
    ("recursion-and-induction", "python-algorithms", "Recursão e indução",
     "Somar uma estrutura arbitrariamente aninhada de inteiros e listas.",
     "A recursão requer um caso base e uma redução estrita. A prova indutiva segue a mesma estrutura da implementação.",
     "def soma_aninhada(valor):\n    pass\n",
     "assert soma_aninhada(4) == 4\nassert soma_aninhada([1,[2,3],[],4]) == 10\nassert soma_aninhada([]) == 0"),
    ("dynamic-programming", "python-algorithms", "Programação dinâmica",
     "Calcular o custo mínimo para subir degraus com custos não negativos.",
     "Define estado, transição e casos base. Guardar apenas estados necessários evita repetir subproblemas e pode reduzir a memória.",
     "def custo_minimo_degraus(custos):\n    pass\n",
     "assert custo_minimo_degraus([10,15,20]) == 15\nassert custo_minimo_degraus([1,100,1,1,1,100,1,1,100,1]) == 6\nassert custo_minimo_degraus([]) == 0"),
    ("graph-traversal", "python-algorithms", "Percurso de grafos",
     "Devolver a menor distância em arestas num grafo não ponderado.",
     "BFS explora por camadas. A primeira visita de um nó estabelece a menor quantidade de arestas desde a origem.",
     "def distancia_bfs(grafo, origem, destino):\n    pass\n",
     "g={'A':['B','C'],'B':['D'],'C':['D'],'D':[]}\nassert distancia_bfs(g,'A','D') == 2\nassert distancia_bfs(g,'A','A') == 0\nassert distancia_bfs(g,'D','A') is None"),
    ("stacks-and-queues", "python-data-structures", "Pilhas e filas",
     "Validar delimitadores com uma pilha e rejeitar fechos fora de ordem.",
     "A pilha representa dependências aninhadas: o último delimitador aberto deve ser o primeiro a fechar.",
     "def delimitadores_validos(texto):\n    pass\n",
     "assert delimitadores_validos('a[(b+c)*d]')\nassert not delimitadores_validos('([)]')\nassert not delimitadores_validos('(()')\nassert delimitadores_validos('')"),
    ("linked-nodes", "python-data-structures", "Nós ligados",
     "Implementar append e conversão para lista numa lista simplesmente ligada.",
     "Uma estrutura ligada conserva identidade e ligações em vez de contiguidade. Cabeça, cauda e tamanho devem mudar de forma consistente.",
     "class ListaLigada:\n    pass\n",
     "l=ListaLigada()\nassert l.para_lista() == []\nl.append(2); l.append(5)\nassert l.para_lista() == [2,5]\nassert len(l) == 2"),
    ("hash-index", "python-data-structures", "Índices por dispersão",
     "Construir um índice invertido que associa cada termo aos documentos onde ocorre.",
     "Um mapa de conjuntos combina acesso por chave com unicidade. Normalizar antes de indexar evita chaves equivalentes separadas.",
     "def indice_invertido(documentos):\n    pass\n",
     "i=indice_invertido({'a':'Sol e mar','b':'mar azul'})\nassert i['mar'] == {'a','b'}\nassert i['sol'] == {'a'}\nassert i['azul'] == {'b'}"),
    ("heaps-and-priority", "python-data-structures", "Heaps e prioridade",
     "Selecionar os k menores valores sem ordenar toda a entrada.",
     "Um heap mantém o melhor candidato na raiz. A estrutura é útil quando apenas uma fração ordenada do conjunto é necessária.",
     "def k_menores(valores, k):\n    pass\n",
     "assert k_menores([7,2,9,1,5],3) == [1,2,5]\nassert k_menores([2,1],0) == []\nassert k_menores([2,1],5) == [1,2]"),
    ("binary-search-trees", "python-data-structures", "Árvores de pesquisa",
     "Inserir valores numa árvore binária e devolver o percurso em ordem sem repetições.",
     "A propriedade esquerda < nó < direita permite pesquisa e percurso ordenado. Uma política explícita decide o tratamento de duplicados.",
     "class ArvorePesquisa:\n    pass\n",
     "a=ArvorePesquisa()\nfor n in [5,3,7,3,6]: a.inserir(n)\nassert a.em_ordem() == [3,5,6,7]\nassert a.contem(6)\nassert not a.contem(4)"),
    ("union-find", "python-data-structures", "Conjuntos disjuntos",
     "Manter componentes com union e connected usando compressão de caminhos.",
     "Union-Find representa uma floresta. Compressão de caminhos e união por tamanho reduzem a altura sem mudar as componentes.",
     "class UnionFind:\n    pass\n",
     "u=UnionFind(5)\nassert not u.connected(0,1)\nu.union(0,1); u.union(1,2)\nassert u.connected(0,2)\nassert not u.connected(0,4)\nassert u.componentes == 3"),
)


ACADEMY_MODULES = (*_ACADEMY_MODULES_BASE, *VERTICAL_CORE_MODULES)
