"""Original, source-linked learning facts and glossary expansion.

The text in this module is authored for Aprendix.  References are identifiers
for bibliographic metadata; no protected source text is reproduced.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class FactDefinition:
    slug: str
    area_id: str
    fact: str
    explanation: str
    formula_or_code: str = ""
    complexity: str = "beginner"
    source_ids: tuple[str, ...] = ()


FACTS: tuple[FactDefinition, ...] = (
    FactDefinition("modulo-paridade", "prog-foundations", "O resto da divisão por 2 permite testar a paridade de um inteiro.", "`n % 2` vale zero quando `n` é par e um quando é ímpar. O operador `%` calcula o resto; não realiza uma divisão por zero.", "par = (n % 2 == 0)", source_ids=("src-python-docs",)),
    FactDefinition("truthiness", "prog-foundations", "Python permite testar coleções vazias diretamente numa condição.", "Listas, dicionários, conjuntos e strings vazios são falsos; coleções não vazias são verdadeiras. Isto evita comparações redundantes com zero.", "if resultados:\n    print('há dados')", source_ids=("src-python-docs", "src-fluent-python")),
    FactDefinition("generator-lazy", "python", "Um generator pode representar uma sequência maior do que a memória disponível.", "Os valores são produzidos sob pedido e não guardados todos de uma vez. A vantagem desaparece se o generator for imediatamente convertido numa lista.", "quadrados = (n * n for n in range(1_000_000))", source_ids=("src-python-docs", "src-fluent-python")),
    FactDefinition("mutable-default", "python", "Um argumento predefinido mutável é criado uma única vez, não em cada chamada.", "Usa `None` como sentinela e cria a lista dentro da função para impedir que chamadas independentes partilhem estado acidentalmente.", "def adicionar(x, itens=None):\n    itens = [] if itens is None else itens", "intermediate", ("src-python-docs", "src-fluent-python")),
    FactDefinition("composition", "oop", "Composição costuma preservar melhor o encapsulamento do que uma hierarquia profunda.", "Um objeto recebe colaboradores com contratos pequenos. Assim, cada parte pode ser substituída ou testada sem herdar estado e comportamento que não usa.", "class Relatorio:\n    def __init__(self, repositorio):\n        self.repositorio = repositorio", "intermediate", ("src-python-docs",)),
    FactDefinition("dataclass", "oop", "Uma dataclass gera operações de dados sem esconder as regras do domínio.", "É adequada para valores e registos. Invariantes continuam a pertencer a métodos explícitos ou a `__post_init__`.", "@dataclass(frozen=True)\nclass Ponto:\n    x: float\n    y: float", "intermediate", ("src-python-docs",)),
    FactDefinition("set-membership", "data-structures", "Um `set` troca ordem e repetição por testes médios de pertença muito rápidos.", "A procura média é O(1), enquanto procurar numa lista é O(n). Mantém também uma lista quando a ordem de primeira ocorrência fizer parte do resultado.", "vistos = set()\nif item not in vistos: vistos.add(item)", source_ids=("src-python-docs", "src-clrs")),
    FactDefinition("hash-collisions", "data-structures", "Duas chaves podem ter o mesmo hash sem serem a mesma chave.", "A tabela de dispersão resolve colisões e confirma igualdade. Por isso, objetos mutáveis não devem ser usados como chaves se o seu hash puder mudar.", "hash(chave)", "intermediate", ("src-python-docs", "src-clrs")),
    FactDefinition("binary-search", "classic-algorithms", "Pesquisa binária elimina metade do espaço a cada passo.", "Exige uma coleção ordenada e limites atualizados sem perder o alvo. O número de comparações cresce como O(log n).", "meio = inicio + (fim - inicio) // 2", source_ids=("src-clrs",)),
    FactDefinition("big-o-constants", "classic-algorithms", "Big-O descreve crescimento, não o tempo real isolado.", "Dois algoritmos O(n) podem ter custos constantes muito diferentes. Mede entradas representativas depois de escolher uma classe de complexidade adequada.", "T(n) = 3n + 8 ∈ O(n)", "intermediate", ("src-clrs",)),
    FactDefinition("tests-boundaries", "software-engineering", "Um teste de fronteira revela pressupostos que um exemplo médio costuma esconder.", "Para cada contrato, testa vazio, mínimo, máximo razoável, repetição e falha esperada. Um teste deve produzir sempre a mesma evidência.", "assert dividir([], 2) == []", source_ids=("src-python-docs",)),
    FactDefinition("database-index", "databases", "Um índice acelera leituras específicas, mas cobra espaço e trabalho em cada escrita.", "Escolhe índices a partir das consultas reais. A ordem das colunas num índice composto altera quais filtros e ordenações podem aproveitá-lo.", "CREATE INDEX idx_evento_user_data ON eventos(user_id, data);", "intermediate", ("src-postgresql",)),
    FactDefinition("transaction-atomic", "databases", "Uma transação transforma várias escritas numa única decisão: confirmar tudo ou nada.", "Atomicidade não substitui isolamento. Em concorrência, seleciona o nível de isolamento e mantém transações curtas para reduzir bloqueios.", "BEGIN;\nUPDATE ...;\nCOMMIT;", "intermediate", ("src-postgresql",)),
    FactDefinition("semantic-html", "web", "HTML semântico melhora acessibilidade antes de qualquer CSS.", "Elementos como `nav`, `main`, `button` e títulos comunicam estrutura a leitores de ecrã e ferramentas automáticas.", "<button type=\"button\">Executar</button>", source_ids=("src-mdn",)),
    FactDefinition("async-not-parallel", "systems", "Concorrência assíncrona não significa execução paralela de CPU.", "`asyncio` é eficaz quando tarefas esperam por I/O. Trabalho intensivo de CPU exige processos, extensões nativas ou outra estratégia de paralelismo.", "resultado = await pedido()", "intermediate", ("src-python-docs",)),
    FactDefinition("dot-product", "linear-algebra", "O produto interno mede alinhamento e também calcula a entrada de um neurónio.", "Multiplica componentes correspondentes e soma. Se os vetores forem normalizados, o produto interno coincide com a similaridade do cosseno.", "x·w = Σᵢ xᵢwᵢ", "intermediate", ("src-dlbook", "src-probml")),
    FactDefinition("chain-rule", "calculus", "Backpropagation é uma aplicação organizada da regra da cadeia.", "Cada operação local fornece uma derivada; o gradiente total resulta do produto desses efeitos ao longo do grafo computacional.", "∂L/∂x = (∂L/∂y)(∂y/∂x)", "intermediate", ("src-dlbook", "src-pytorch-autograd")),
    FactDefinition("bayes", "probability", "Bayes combina conhecimento anterior com a evidência observada.", "A posterior é proporcional à verosimilhança vezes a prior. A constante de normalização garante que as probabilidades somam um.", "P(H|D) = P(D|H)P(H) / P(D)", "intermediate", ("src-probml",)),
    FactDefinition("learning-rate", "optimization", "Uma taxa de aprendizagem demasiado grande pode aumentar a perda mesmo com o gradiente correto.", "O gradiente indica direção local; a taxa define o tamanho do passo. Compara curvas de treino e validação e verifica escalas das variáveis.", "θ ← θ − η∇L(θ)", "intermediate", ("src-dlbook",)),
    FactDefinition("data-leakage", "data-practice", "Pré-processar antes de separar treino e validação pode revelar o futuro ao modelo.", "Ajusta imputação, normalização e seleção apenas nos dados de treino. Pipelines aplicam depois a transformação aprendida à validação.", "Pipeline([('scale', StandardScaler()), ('model', SVC())])", "intermediate", ("src-sklearn", "src-pandas")),
    FactDefinition("a-star", "ai-foundations", "A* encontra um caminho ótimo quando a heurística nunca sobrestima o custo restante.", "A prioridade combina custo já pago `g` e estimativa `h`. Uma heurística mais informativa reduz expansões sem perder a garantia quando é admissível.", "f(n) = g(n) + h(n)", "advanced", ("src-aima",)),
    FactDefinition("cross-validation", "classical-ml", "Cross-validation estima variação; não transforma validação em dados de treino.", "Toda a escolha de hiperparâmetros ocorre dentro dos folds. Mantém um teste final intocado para a última estimativa.", "score = cross_val_score(modelo, X, y, cv=5)", "intermediate", ("src-sklearn", "src-esl")),
    FactDefinition("uncertainty", "probabilistic-ml", "Uma probabilidade prevista não é automaticamente uma probabilidade calibrada.", "Entre casos anunciados com 80%, aproximadamente 80% deveriam ocorrer. Verifica curvas de calibração e qualidade fora da amostra.", "P(y=1|x)=0.8", "advanced", ("src-probml",)),
    FactDefinition("bagging", "ensemble-learning", "Bagging reduz variância ao combinar modelos treinados em amostras diferentes.", "A média suaviza erros não perfeitamente correlacionados. Se todos os modelos errarem da mesma forma, o benefício diminui.", "ŷ = (1/M) Σₘ fₘ(x)", "intermediate", ("src-esl", "src-sklearn")),
    FactDefinition("neuron", "neural-networks", "Um neurónio artificial aplica uma transformação linear e depois uma não linearidade.", "Os pesos selecionam e combinam sinais; o bias desloca a fronteira; a ativação permite que camadas compostas representem relações não lineares.", "z = w·x + b;  a = φ(z)", source_ids=("src-dlbook",)),
    FactDefinition("backprop", "deep-learning", "Backpropagation reutiliza derivadas intermédias em vez de recalcular cada caminho.", "O forward guarda valores necessários; o backward propaga gradientes da perda para cada parâmetro pelo grafo invertido.", "∂L/∂w = (∂L/∂a)(∂a/∂z)(∂z/∂w)", "advanced", ("src-dlbook", "src-pytorch-autograd")),
    FactDefinition("cnn-sharing", "convolutional-networks", "Uma convolução usa os mesmos pesos em várias posições da imagem.", "A partilha reduz parâmetros e permite detetar o mesmo padrão em locais diferentes. Padding, stride e tamanho do kernel determinam a geometria da saída.", "H_out = ⌊(H+2P−K)/S⌋+1", "intermediate", ("src-resnet", "src-dlbook")),
    FactDefinition("lstm-gates", "sequence-models", "Uma LSTM controla explicitamente o que esquece, escreve e expõe.", "As portas usam valores entre zero e um para modular a memória. Isso melhora o fluxo de gradiente, mas não elimina todos os problemas de sequências longas.", "cₜ = fₜ⊙cₜ₋₁ + iₜ⊙gₜ", "advanced", ("src-dlbook",)),
    FactDefinition("scaled-attention", "transformers", "A atenção divide os produtos internos por √d para evitar softmax excessivamente saturado.", "Queries comparam-se com keys; os pesos normalizados combinam values. Máscaras impedem acesso a posições proibidas.", "Attention(Q,K,V)=softmax(QKᵀ/√dₖ)V", "advanced", ("src-attention",)),
    FactDefinition("diffusion", "generative-ai", "Um modelo de difusão aprende a inverter gradualmente um processo de adição de ruído.", "O treino prevê ruído ou uma grandeza equivalente; a geração começa em ruído e executa vários passos de remoção condicionada.", "xₜ → xₜ₋₁ → … → x₀", "advanced", ("src-dlbook",)),
    FactDefinition("iou", "computer-vision", "Intersection over Union compara a sobreposição entre previsão e referência.", "A métrica divide a área de interseção pela união. Em deteção, um limiar de IoU ajuda a decidir se uma caixa corresponde ao objeto.", "IoU = |A∩B| / |A∪B|", "intermediate", ("src-resnet", "src-vit")),
    FactDefinition("tokenization", "natural-language", "Um modelo de linguagem normalmente recebe tokens, não palavras completas.", "Subpalavras equilibram vocabulário e cobertura. Uma alteração pequena no texto pode produzir uma sequência de tokens diferente.", "texto → ids de tokens → embeddings", "intermediate", ("src-attention", "src-rag")),
    FactDefinition("bellman", "reinforcement-learning", "A equação de Bellman separa recompensa imediata de valor futuro descontado.", "Ela torna um problema sequencial recursivo. O fator γ controla quanto as consequências futuras influenciam a decisão atual.", "V(s)=E[r+γV(s′)]", "advanced", ("src-rlbook",)),
    FactDefinition("agent-loop", "autonomous-agents", "Um agente fiável separa observação, decisão, ação e verificação.", "Cada ferramenta deve ter contrato, limite e resultado observável. A verificação impede que uma resposta textual seja confundida com uma ação realmente executada.", "observar → planear → agir → verificar", "intermediate", ("src-aima", "src-react")),
    FactDefinition("react-loop", "agent-architectures", "ReAct intercala raciocínio operacional com observações reais das ferramentas.", "O plano é revisto depois de cada resultado. Trajetórias limitadas e auditáveis são mais seguras do que ciclos sem condição de paragem.", "pensamento → ação → observação", "advanced", ("src-react", "src-reflexion")),
    FactDefinition("episodic-memory", "agent-memory", "Memória episódica guarda experiências; memória semântica guarda conhecimento consolidado.", "Recuperar tudo aumenta ruído e custo. Um agente deve selecionar memórias por relevância, atualidade e confiança.", "score = relevância × confiança × recência", "advanced", ("src-reflexion", "src-generative-agents")),
    FactDefinition("multi-agent", "multi-agent", "Mais agentes não garantem uma solução melhor.", "A coordenação acrescenta mensagens, conflitos e duplicação. Papéis claros e uma regra de agregação verificável são essenciais.", "resultado = agregar(propostas, evidência)", "advanced", ("src-generative-agents", "src-aima")),
    FactDefinition("agent-eval", "agent-evaluation", "Avaliar apenas a resposta final esconde ações inseguras no percurso.", "Mede sucesso, custo, chamadas inválidas, recuperação de erros e necessidade de intervenção humana por trajetória.", "taxa_sucesso, custo, violações, recuperação", "advanced", ("src-react", "src-ai-index")),
    FactDefinition("calibration-fairness", "responsible-ai", "Precisão global pode esconder falhas graves num subgrupo.", "Compara erro, calibração e cobertura entre grupos relevantes e documenta incerteza. A métrica adequada depende do dano possível.", "erro_grupo = falhas_grupo / casos_grupo", "advanced", ("src-ai-index",)),
    FactDefinition("finance-split", "finance-app", "Em finanças, dividir dados aleatoriamente pode ensinar o futuro ao passado.", "Usa divisões temporais e inclui custos, atrasos e survivorship bias. Uma estratégia só é avaliada em períodos posteriores ao treino.", "treino < validação < teste no tempo", "advanced", ("src-esl",)),
    FactDefinition("medical-metrics", "health-app", "Sensibilidade e especificidade respondem a perguntas diferentes.", "Sensibilidade mede positivos detetados; especificidade mede negativos corretamente rejeitados. O limiar deve refletir custos clínicos e prevalência.", "sensibilidade = TP/(TP+FN)", "intermediate", ("src-unet",)),
    FactDefinition("pid", "robotics-app", "Um controlador PID combina erro atual, acumulado e tendência do erro.", "O termo proporcional reage, o integral remove erro persistente e o derivativo amortece mudanças rápidas. Saturação exige anti-windup.", "u=Kₚe+Kᵢ∫e dt+K_d de/dt", "advanced", ("src-aima",)),
    FactDefinition("game-delta", "games-app", "Movimento dependente do número de frames muda de velocidade entre computadores.", "Multiplica velocidades pelo tempo decorrido e limita saltos muito grandes. A simulação pode usar passos fixos separados do desenho.", "posição += velocidade × delta_t", "intermediate", ("src-clrs",)),
    FactDefinition("implicit-feedback", "recommendation-app", "Um clique é feedback implícito, não uma declaração inequívoca de preferência.", "Posição, exposição e curiosidade influenciam o clique. Mantém uma linha de base e distingue não observado de rejeitado.", "score(u,i)=afinidade−viés_exposição", "advanced", ("src-esl",)),
    FactDefinition("time-validation", "time-series-app", "Validação temporal nunca deve baralhar observações futuras para o treino.", "Expanding windows simulam a informação disponível em cada data. Compara sempre com baselines sazonais simples.", "train[:t] → validate[t:t+h]", "intermediate", ("src-probml",)),
    FactDefinition("least-privilege", "cybersecurity-app", "Código deve receber apenas as permissões necessárias durante o menor tempo possível.", "Isolamento, allowlists e limites de recursos reduzem impacto mesmo quando há um erro. Validação de entrada não substitui sandboxing.", "permissões = mínimo(necessário)", "intermediate", ("src-python-docs",)),
    FactDefinition("numerical-stability", "science-app", "Expressões matematicamente equivalentes podem ter erros numéricos muito diferentes.", "Evita subtrair números quase iguais e acompanha escala, unidade e condicionamento. Valida com casos de referência.", "logsumexp(x)=m+log Σ exp(xᵢ−m)", "advanced", ("src-numpy",)),
    FactDefinition("quantization", "edge-mobile-app", "Quantização int8 reduz aproximadamente quatro vezes o armazenamento face a float32.", "O ganho real depende de operadores e hardware. Mede erro por camada e calibra com dados representativos antes de aceitar o modelo.", "real ≈ escala × (q − zero_point)", "advanced", ("src-pytorch-autograd", "src-ai-index")),
)


# term, technology, concise definition, signature, example, related terms
EXTRA_GLOSSARY: tuple[tuple[str, str, str, str, str, tuple[str, ...]], ...] = (
    ("else", "python", "Introduz o ramo executado quando a condição anterior é falsa, ou o bloco final de certas estruturas de repetição e exceção.", "else:", "if saldo >= custo:\n    pagar()\nelse:\n    avisar()", ("if", "elif", "for", "try")),
    ("elif", "python", "Testa uma condição adicional quando os ramos anteriores de um `if` não foram escolhidos.", "elif condição:", "if n < 0: ...\nelif n == 0: ...", ("if", "else")),
    ("try", "python", "Delimita operações cujas exceções serão tratadas por blocos `except`, `else` ou `finally`.", "try: ... except TipoErro: ...", "try:\n    valor = int(texto)\nexcept ValueError:\n    valor = 0", ("except", "finally", "exception")),
    ("except", "python", "Trata apenas os tipos de exceção explicitamente indicados depois de uma operação protegida.", "except TipoErro as erro:", "except ValueError as erro:\n    print(erro)", ("try", "raise", "finally")),
    ("finally", "python", "Executa limpeza quer exista uma exceção quer a operação termine normalmente.", "finally:", "try:\n    usar()\nfinally:\n    fechar()", ("try", "with")),
    ("with", "python", "Usa um context manager para adquirir e libertar um recurso de forma determinística.", "with expressão as nome:", "with open(caminho) as ficheiro:\n    texto = ficheiro.read()", ("context manager", "finally", "open")),
    ("lambda", "python", "Cria uma função anónima limitada a uma única expressão.", "lambda argumentos: expressão", "chave = lambda item: item.preco", ("def", "function")),
    ("yield", "python", "Suspende uma função generator e entrega um valor, preservando o seu estado para a continuação.", "yield valor", "def pares():\n    for n in range(4):\n        if n % 2 == 0: yield n", ("generator", "iterator")),
    ("async", "python", "Declara código assíncrono que pode suspender cooperativamente em operações aguardáveis.", "async def função(...):", "async def obter():\n    return await pedido()", ("await", "asyncio")),
    ("await", "python", "Suspende a coroutine atual até um awaitable terminar, permitindo que o event loop avance outras tarefas.", "await awaitable", "resposta = await cliente.get(url)", ("async", "coroutine")),
    ("break", "python", "Termina imediatamente o ciclo `for` ou `while` mais interior.", "break", "for item in dados:\n    if item == alvo: break", ("continue", "for", "while")),
    ("continue", "python", "Salta o restante corpo da iteração atual e avança para a próxima.", "continue", "if inválido:\n    continue", ("break", "for", "while")),
    ("pass", "python", "Instrução que não executa operação alguma, usada onde a sintaxe exige um bloco.", "pass", "class Marcador:\n    pass", ("class", "def")),
    ("in", "python", "Testa pertença ou participa na iteração sobre os elementos de um objeto.", "elemento in coleção", "if chave in mapa: ...", ("set", "for")),
    ("is", "python", "Compara identidade de objetos; não substitui `==` para igualdade de valores.", "objeto is outro", "if resultado is None: ...", ("None", "equality")),
    ("None", "python", "Objeto singleton usado para representar ausência explícita de valor.", "None", "resultado = None", ("is", "optional")),
    ("match", "python", "Inicia pattern matching estrutural sobre a forma e os valores de um objeto.", "match valor:", "match ponto:\n    case (0, y): ...", ("case", "if")),
    ("case", "python", "Define um padrão possível dentro de uma instrução `match`.", "case padrão [if guarda]:", "case {'estado': 'ok'}: ...", ("match", "pattern")),
    ("assert", "python", "Verifica uma condição de desenvolvimento e lança `AssertionError` se for falsa; não valida input hostil em produção.", "assert condição, mensagem", "assert total >= 0", ("test", "raise")),
    ("raise", "python", "Interrompe o fluxo normal lançando uma exceção explícita.", "raise TipoErro(mensagem)", "raise ValueError('idade inválida')", ("exception", "try")),
    ("import", "python", "Carrega um módulo e liga um nome ao respetivo objeto de módulo ou membro.", "import módulo", "import math", ("module", "from")),
    ("from", "python", "Seleciona membros ou uma base relativa ao importar, e também aparece em `yield from`.", "from módulo import nome", "from pathlib import Path", ("import", "module")),
    ("all", "python", "Devolve verdadeiro quando todos os elementos são verdadeiros; numa coleção vazia devolve verdadeiro.", "all(iterável)", "all(n > 0 for n in valores)", ("any", "bool")),
    ("any", "python", "Devolve verdadeiro quando pelo menos um elemento é verdadeiro; numa coleção vazia devolve falso.", "any(iterável)", "any(erro for erro in erros)", ("all", "bool")),
    ("abs", "python", "Devolve o valor absoluto de um número ou usa o protocolo `__abs__` do objeto.", "abs(x)", "abs(-4)  # 4", ("math", "number")),
    ("isinstance", "python", "Testa se um objeto pertence a um tipo ou a uma hierarquia de tipos.", "isinstance(objeto, tipo)", "isinstance(valor, (int, float))", ("type", "class")),
    ("map", "python", "Produz preguiçosamente a aplicação de uma função a elementos de um ou mais iteráveis.", "map(função, iterável, ...)", "map(str.upper, nomes)", ("filter", "iterator")),
    ("filter", "python", "Produz os elementos para os quais um predicado é verdadeiro.", "filter(predicado, iterável)", "filter(str.isdigit, textos)", ("map", "iterator")),
    ("min", "python", "Seleciona o menor elemento ou o elemento com menor chave calculada.", "min(iterável, key=None)", "min(pessoas, key=lambda p: p.idade)", ("max", "sorted")),
    ("max", "python", "Seleciona o maior elemento ou o elemento com maior chave calculada.", "max(iterável, key=None)", "max(notas, default=0)", ("min", "sorted")),
    ("open", "python", "Abre um fluxo de ficheiro com modo e encoding explícitos; deve normalmente ser usado num `with`.", "open(path, mode='r', encoding=None)", "with open(path, encoding='utf-8') as f: ...", ("with", "pathlib")),
    ("property", "python", "Expõe métodos de acesso através da sintaxe de atributo, preservando um contrato público.", "property(fget, fset=None)", "@property\ndef total(self): return self._total", ("descriptor", "class")),
    ("super", "python", "Continua a procura de métodos pela ordem de resolução da classe, permitindo cooperação entre classes.", "super().método(...)", "super().__init__()", ("inheritance", "MRO")),
    ("pathlib", "python", "Módulo da biblioteca padrão para manipular caminhos como objetos portáveis.", "Path(caminho)", "ficheiros = Path('.').glob('*.py')", ("open", "filesystem")),
    ("dataclass", "python", "Decorador que gera inicialização, representação e comparação para classes orientadas a dados.", "@dataclass", "@dataclass(frozen=True)\nclass Ponto: x: float", ("class", "typing")),
    ("decorator", "python", "Função que recebe um objeto definido e devolve o objeto usado no seu lugar.", "@decorador", "@cache\ndef calcular(x): ...", ("function", "closure")),
    ("iterator", "python", "Objeto que entrega um elemento de cada vez através de `__next__` e sinaliza o fim com `StopIteration`.", "iter(objeto); next(iterator)", "it = iter([1, 2])", ("iterable", "generator")),
    ("generator", "python", "Iterator criado por uma função com `yield` ou por uma expressão generator.", "(expressão for item in iterável)", "quadrados = (n*n for n in dados)", ("yield", "iterator")),
    ("recursão", "algorithms", "Técnica em que uma função resolve o problema usando instâncias menores do mesmo problema e um caso base.", "T(n) = T(n-1) + custo", "def f(n): return 1 if n <= 1 else n*f(n-1)", ("stack", "dynamic programming")),
    ("complexidade temporal", "algorithms", "Descrição do crescimento do número de operações em função do tamanho da entrada.", "O(f(n))", "pesquisa binária: O(log n)", ("Big-O", "complexidade espacial")),
    ("pesquisa binária", "algorithms", "Procura num domínio ordenado descartando metade do intervalo em cada passo.", "O(log n)", "meio = (inicio + fim) // 2", ("sorting", "invariant")),
    ("BFS", "algorithms", "Pesquisa em largura que visita um grafo por níveis usando uma fila.", "O(V+E)", "fila.append(origem)", ("DFS", "queue", "graph")),
    ("DFS", "algorithms", "Pesquisa em profundidade que explora um ramo antes de regressar, com pilha explícita ou recursão.", "O(V+E)", "pilha = [origem]", ("BFS", "stack", "graph")),
    ("programação dinâmica", "algorithms", "Resolve subproblemas sobrepostos uma vez e reutiliza os resultados.", "estado + transição + caso base", "dp[i] = min(dp[i-1], dp[i-2]) + custo[i]", ("memoization", "recursão")),
    ("produto interno", "mathematics", "Soma dos produtos entre componentes correspondentes de dois vetores.", "x·w = Σᵢxᵢwᵢ", "score = sum(a*b for a,b in zip(x,w))", ("vetor", "cosine similarity")),
    ("derivada", "mathematics", "Taxa de variação local de uma função relativamente a uma variável.", "f′(x)=limₕ→0 [f(x+h)−f(x)]/h", "d(x²)/dx = 2x", ("gradiente", "regra da cadeia")),
    ("regra da cadeia", "mathematics", "Calcula a derivada de uma composição multiplicando derivadas locais.", "d f(g(x))/dx = f′(g(x))g′(x)", "backpropagation", ("derivada", "backpropagation")),
    ("variância", "statistics", "Média do quadrado dos desvios face à média, usada para quantificar dispersão.", "Var(X)=E[(X−μ)²]", "statistics.pvariance(valores)", ("média", "desvio padrão")),
    ("desvio padrão", "statistics", "Raiz quadrada da variância, expressa na mesma unidade dos dados.", "σ=√Var(X)", "statistics.pstdev(valores)", ("variância", "distribuição")),
    ("precisão", "machine-learning", "Proporção das previsões positivas que são realmente positivas.", "precision=TP/(TP+FP)", "avaliar falsos positivos", ("recall", "F1")),
    ("recall", "machine-learning", "Proporção dos positivos reais que o modelo conseguiu detetar.", "recall=TP/(TP+FN)", "avaliar falsos negativos", ("precisão", "sensibilidade", "F1")),
    ("F1", "machine-learning", "Média harmónica entre precisão e recall, útil quando ambos importam.", "F1=2PR/(P+R)", "f1_score(y_true, y_pred)", ("precisão", "recall")),
    ("cross-validation", "machine-learning", "Avaliação repetida em folds que estima desempenho e variação fora da amostra.", "K folds", "cross_val_score(modelo, X, y, cv=5)", ("train/test split", "data leakage")),
    ("data leakage", "machine-learning", "Uso acidental de informação indisponível no momento real da previsão.", "treino não pode observar validação/futuro", "ajustar scaler apenas no treino", ("cross-validation", "pipeline")),
    ("regularização", "machine-learning", "Restrição ou penalização que reduz soluções excessivamente ajustadas ao treino.", "L_total=L_dados+λR(θ)", "L2: λ||θ||²", ("overfitting", "loss")),
    ("feedforward", "deep-learning", "Passagem das entradas pelas camadas até à previsão, sem calcular ainda os gradientes.", "aˡ=φ(Wˡaˡ⁻¹+bˡ)", "previsão = modelo(x)", ("backpropagation", "rede neuronal")),
    ("ReLU", "deep-learning", "Ativação que mantém valores positivos e substitui negativos por zero.", "ReLU(x)=max(0,x)", "torch.relu(x)", ("activation", "sigmoid")),
    ("softmax", "deep-learning", "Transforma logits num vetor positivo que soma um, sensível a diferenças relativas.", "softmax(zᵢ)=exp(zᵢ)/Σⱼexp(zⱼ)", "probabilidades de classes", ("logit", "cross-entropy")),
    ("CNN", "deep-learning", "Rede que aplica filtros partilhados localmente, muito usada em dados espaciais.", "feature=input*kernel", "Conv2D(canais, filtros, kernel)", ("convolução", "computer vision")),
    ("RNN", "deep-learning", "Rede que atualiza um estado oculto ao percorrer uma sequência.", "hₜ=f(xₜ,hₜ₋₁)", "sequência → estados", ("LSTM", "sequence")),
    ("LSTM", "deep-learning", "RNN com portas que regulam escrita, esquecimento e leitura de memória.", "cₜ=fₜcₜ₋₁+iₜgₜ", "Long Short-Term Memory", ("RNN", "GRU")),
    ("RAG", "artificial-intelligence", "Arquitetura que recupera evidência antes de sintetizar uma resposta condicionada.", "pergunta → retrieval → contexto → síntese", "citar chunks recuperados", ("embedding", "information retrieval")),
    ("ReAct", "artificial-intelligence", "Padrão de agente que intercala raciocínio operacional, ação e nova observação.", "reason → act → observe", "usar ferramenta e verificar resultado", ("agente", "tool use", "Reflexion")),
    ("IoU", "computer-vision", "Razão entre interseção e união de duas regiões, usada em deteção e segmentação.", "IoU=|A∩B|/|A∪B|", "comparar máscara prevista e real", ("segmentação", "object detection")),
)
