"""Minimal, versioned JSON contracts used between Aprendix modules."""

from aprendix.application.contracts.models import (
    AttemptDTO,
    EventDTO,
    ExerciseDTO,
    GraphEdgeDTO,
    GraphNodeDTO,
    ProfileDTO,
    UserDTO,
)
from aprendix.application.contracts.commands import (
    SubmissionReceipt,
    SubmitAttemptCommand,
)
from aprendix.application.contracts.graph import (
    GraphEdgeSnapshotDTO,
    GraphNodeSnapshotDTO,
    GraphSnapshotDTO,
    NodeStatisticsDTO,
    RecommendationDTO,
)
from aprendix.application.contracts.copykate import (
    AlternativeSolutionDTO,
    AstChangeDTO,
    CodeEditDTO,
    CopyKateRequest,
    CopyKateResponse,
    ImitationProfileDTO,
    NGramTransitionDTO,
    PolicyViolationDTO,
    SandboxRequest,
    SandboxResult,
)
from aprendix.application.contracts.content import (
    ConstraintKind,
    ExerciseConstraintDTO,
    ExerciseTemplateDTO,
    FadedHintDTO,
    FallbackReason,
    GeneratedExerciseDTO,
    GenerateExerciseRequest,
    HintSource,
    HintStage,
    HintTemplateDTO,
    NLPHintRequestDTO,
    NLPHintResponseDTO,
    TemplateParameterDTO,
)
from aprendix.application.contracts.knowledge import (
    Complexity,
    ContentKind,
    DashboardDTO,
    DashboardNodeDTO,
    EvidenceOrigin,
    GradingTestCaseDTO,
    GradingTestOutcomeDTO, GradingRubricDTO,
    IngestionSummaryDTO,
    CuratedSourceDTO,
    KnowledgeAreaDTO,
    KnowledgeClusterDTO,
    LearningMode,
    LearningTheme,
    ReadingConceptDTO,
    ReadingDetailDTO,
    SearchEvidenceDTO,
    SearchFiltersDTO,
    SearchRequestDTO,
    SearchResponseDTO,
    SearchIntent,
    SearchShortcutDTO,
    SmartCorrectionRequestDTO,
    SmartCorrectionResponseDTO,
    TheoryCardDTO,
    Technology,
)
from aprendix.application.contracts.desktop import (
    EvaluationReceiptDTO,
    LearnerRank,
    MilestoneProgressDTO,
    ProjectDTO,
)
from aprendix.application.contracts.platform import (
    BaselineMetricDTO,
    ComponentHealthDTO,
    DiagnosticEventDTO,
    DiagnosticSeverity,
    FeatureFlagDTO,
    HealthStatus,
    RuntimeHealthDTO,
    sanitize_diagnostic_context,
)
from aprendix.application.contracts.progress import (
    ErrorCategory,
    EvidenceType,
    LearningAction,
    LearningEvidenceDTO,
    MasteryStateDTO,
    NextLearningActionDTO,
    PersonalProgressDTO,
    WeeklyPlanItemDTO,
)
from aprendix.application.contracts.tutor import (
    TutorRequestDTO, TutorResponseDTO, TutorStrategy,
)
from aprendix.application.contracts.portfolio import (
    PortfolioEntryDTO, ProjectEvaluationDTO, ProjectTemplateDTO,
)
from aprendix.application.contracts.snippet import (
    OcrDraftDTO, OcrRegionDTO, SnippetAction, SnippetAnalysisDTO, SnippetRequestDTO,
)
from aprendix.application.contracts.governance import (
    AuthorityLevel,
    ContentSourceDTO,
    CurriculumCoverageDTO,
    GapCode,
)
from aprendix.application.contracts.debugger import (
    DebugBreakpointDTO,
    DebugFrameDTO,
    DebugRequestDTO,
    DebugSessionDTO,
)

__all__ = [
    "AlternativeSolutionDTO",
    "AttemptDTO",
    "AuthorityLevel",
    "BaselineMetricDTO",
    "AstChangeDTO",
    "CodeEditDTO",
    "Complexity",
    "ComponentHealthDTO",
    "ContentKind",
    "ContentSourceDTO",
    "ConstraintKind",
    "CopyKateRequest",
    "CopyKateResponse",
    "DashboardDTO",
    "DashboardNodeDTO",
    "DiagnosticEventDTO",
    "DiagnosticSeverity",
    "DebugBreakpointDTO",
    "DebugFrameDTO",
    "DebugRequestDTO",
    "DebugSessionDTO",
    "EventDTO",
    "EvaluationReceiptDTO",
    "EvidenceOrigin",
    "ErrorCategory",
    "EvidenceType",
    "ExerciseConstraintDTO",
    "ExerciseDTO",
    "ExerciseTemplateDTO",
    "FadedHintDTO",
    "FallbackReason",
    "FeatureFlagDTO",
    "GeneratedExerciseDTO",
    "GenerateExerciseRequest",
    "GapCode",
    "GraphEdgeDTO",
    "GraphEdgeSnapshotDTO",
    "GraphNodeDTO",
    "GraphNodeSnapshotDTO",
    "GraphSnapshotDTO",
    "GradingTestCaseDTO",
    "GradingTestOutcomeDTO",
    "GradingRubricDTO",
    "HintSource",
    "HintStage",
    "HintTemplateDTO",
    "HealthStatus",
    "ImitationProfileDTO",
    "IngestionSummaryDTO",
    "CuratedSourceDTO",
    "CurriculumCoverageDTO",
    "KnowledgeAreaDTO",
    "KnowledgeClusterDTO",
    "LearningMode",
    "LearningAction",
    "LearningTheme",
    "LearnerRank",
    "MilestoneProgressDTO",
    "MasteryStateDTO",
    "NGramTransitionDTO",
    "NLPHintRequestDTO",
    "NLPHintResponseDTO",
    "NextLearningActionDTO",
    "NodeStatisticsDTO",
    "PolicyViolationDTO",
    "ProfileDTO",
    "PersonalProgressDTO",
    "ProjectDTO",
    "ReadingConceptDTO",
    "ReadingDetailDTO",
    "RecommendationDTO",
    "RuntimeHealthDTO",
    "SearchEvidenceDTO",
    "SearchFiltersDTO",
    "SearchRequestDTO",
    "SearchResponseDTO",
    "SearchIntent",
    "SearchShortcutDTO",
    "SandboxRequest",
    "SandboxResult",
    "SubmissionReceipt",
    "SubmitAttemptCommand",
    "SmartCorrectionRequestDTO",
    "SmartCorrectionResponseDTO",
    "TemplateParameterDTO",
    "TheoryCardDTO",
    "Technology",
    "TutorRequestDTO",
    "TutorResponseDTO",
    "TutorStrategy",
    "PortfolioEntryDTO",
    "ProjectEvaluationDTO",
    "ProjectTemplateDTO",
    "OcrDraftDTO",
    "OcrRegionDTO",
    "SnippetAction",
    "SnippetAnalysisDTO",
    "SnippetRequestDTO",
    "UserDTO",
    "LearningEvidenceDTO",
    "WeeklyPlanItemDTO",
    "sanitize_diagnostic_context",
]
